# Generated by Django 6.1.1 on 2026-09-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_deliverysetting_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysetting',
            name='location',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
