# Generated by Django 6.1.1 on 2026-09-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_deliverysetting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
