# Generated by Django 6.1.1 on 2026-09-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_delivery_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
