# Generated by Django 6.1.1 on 2026-09-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_subtotal_non_negative'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_fee__gte', 0)), name='delivery_fee_non_negative'),
        ),
    ]
