# Generated by Django 6.1.1 on 2026-09-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_price_non_negative'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deliverysetting',
            constraint=models.CheckConstraint(condition=models.Q(('fee__gte', 0)), name='fee_non_negative'),
        ),
    ]
